export default function Header() {
   return (
      <header>
         <nav>
            <ul>
               <li
                  Link
                  to="/fiction"
               >
                  Fiction
               </li>
               <li
                  Link
                  to="/mystery"
               >
                  Mystery
               </li>
               <li
                  Link
                  to="/thriller"
               >
                  Thriller
               </li>
               <li
                  Link
                  to="/romance"
               >
                  Romance
               </li>
               <li
                  Link
                  to="/fantasy"
               >
                  Fantasy
               </li>
               <li
                  Link
                  to="/morality"
               >
                  Morality
               </li>
               <li
                  Link
                  to="/society"
               >
                  Society
               </li>
               <li
                  Link
                  to="/power"
               >
                  Power
               </li>
               <li
                  Link
                  to="/justice"
               >
                  Justice
               </li>
               <li
                  Link
                  to="/adventure"
               >
                  Adventure
               </li>
               <li
                  Link
                  to="/tragedy"
               >
                  Tragedy
               </li>
               <li
                  Link
                  to="/war"
               >
                  War
               </li>
               <li
                  Link
                  to="/philosophy"
               >
                  Philosophy
               </li>
            </ul>
         </nav>
      </header>
   );
}
